namespace ders4
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            header = new Panel();
            universityLabel = new Label();
            titleLabel = new Label();
            travelBox = new GroupBox();
            swapButton = new Button();
            placeTextBox = new TextBox();
            placeLabel = new Label();
            timeTextBox = new MaskedTextBox();
            timeLabel = new Label();
            dateTextBox = new MaskedTextBox();
            dateLabel = new Label();
            toComboBox = new ComboBox();
            toLabel = new Label();
            fromComboBox = new ComboBox();
            fromLabel = new Label();
            personBox = new GroupBox();
            ticketButton = new Button();
            emailTextBox = new TextBox();
            emailLabel = new Label();
            phoneTextBox = new MaskedTextBox();
            phoneLabel = new Label();
            finTextBox = new TextBox();
            finLabel = new Label();
            nameTextBox = new TextBox();
            nameLabel = new Label();
            ticketsListBox = new ListBox();
            deleteButton = new Button();
            exitButton = new Button();
            header.SuspendLayout();
            travelBox.SuspendLayout();
            personBox.SuspendLayout();
            SuspendLayout();
            header.BackColor = Color.White;
            header.Controls.Add(universityLabel);
            header.Controls.Add(titleLabel);
            header.Dock = DockStyle.Top;
            header.Size = new Size(940, 115);
            universityLabel.AutoSize = true;
            universityLabel.Font = new Font("Arial", 27F, FontStyle.Bold);
            universityLabel.ForeColor = Color.DarkRed;
            universityLabel.Location = new Point(18, 28);
            universityLabel.Text = "⚙ | BEU";
            titleLabel.AutoSize = true;
            titleLabel.Font = new Font("Arial", 22F, FontStyle.Bold | FontStyle.Italic);
            titleLabel.Location = new Point(430, 42);
            titleLabel.Text = "BMU Travel";
            travelBox.BackColor = Color.Black;
            travelBox.Controls.Add(swapButton);
            travelBox.Controls.Add(placeTextBox);
            travelBox.Controls.Add(placeLabel);
            travelBox.Controls.Add(timeTextBox);
            travelBox.Controls.Add(timeLabel);
            travelBox.Controls.Add(dateTextBox);
            travelBox.Controls.Add(dateLabel);
            travelBox.Controls.Add(toComboBox);
            travelBox.Controls.Add(toLabel);
            travelBox.Controls.Add(fromComboBox);
            travelBox.Controls.Add(fromLabel);
            travelBox.ForeColor = Color.White;
            travelBox.Location = new Point(40, 128);
            travelBox.Size = new Size(365, 335);
            travelBox.Text = "Travel information";
            fromLabel.AutoSize = true;
            fromLabel.Location = new Point(20, 40);
            fromLabel.Text = "Haradan:";
            fromComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            fromComboBox.Location = new Point(115, 36);
            fromComboBox.Size = new Size(155, 23);
            toLabel.AutoSize = true;
            toLabel.Location = new Point(20, 92);
            toLabel.Text = "Haraya:";
            toComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            toComboBox.Location = new Point(115, 88);
            toComboBox.Size = new Size(155, 23);
            swapButton.BackColor = Color.Teal;
            swapButton.ForeColor = Color.White;
            swapButton.Location = new Point(287, 39);
            swapButton.Size = new Size(55, 90);
            swapButton.Text = "<\r\n>";
            swapButton.Click += swapButton_Click;
            dateLabel.AutoSize = true;
            dateLabel.Location = new Point(20, 145);
            dateLabel.Text = "Tarix:";
            dateTextBox.Location = new Point(115, 141);
            dateTextBox.Mask = "00/00/0000";
            dateTextBox.Size = new Size(155, 23);
            timeLabel.AutoSize = true;
            timeLabel.Location = new Point(20, 197);
            timeLabel.Text = "Saat:";
            timeTextBox.Location = new Point(115, 193);
            timeTextBox.Mask = "00:00";
            timeTextBox.Size = new Size(155, 23);
            placeLabel.AutoSize = true;
            placeLabel.Location = new Point(20, 249);
            placeLabel.Text = "Yer:";
            placeTextBox.Location = new Point(115, 245);
            placeTextBox.Size = new Size(155, 23);
            personBox.BackColor = Color.Black;
            personBox.ForeColor = Color.White;
            personBox.Location = new Point(535, 128);
            personBox.Size = new Size(365, 335);
            personBox.Text = "Person information";
            personBox.Controls.Add(ticketButton);
            personBox.Controls.Add(emailTextBox);
            personBox.Controls.Add(emailLabel);
            personBox.Controls.Add(phoneTextBox);
            personBox.Controls.Add(phoneLabel);
            personBox.Controls.Add(finTextBox);
            personBox.Controls.Add(finLabel);
            personBox.Controls.Add(nameTextBox);
            personBox.Controls.Add(nameLabel);
            nameLabel.AutoSize = true;
            nameLabel.Location = new Point(20, 40);
            nameLabel.Text = "Ad və soyad:";
            nameTextBox.Location = new Point(145, 36);
            nameTextBox.Size = new Size(155, 23);
            finLabel.AutoSize = true;
            finLabel.Location = new Point(20, 92);
            finLabel.Text = "FIN:";
            finTextBox.Location = new Point(145, 88);
            finTextBox.Size = new Size(155, 23);
            phoneLabel.AutoSize = true;
            phoneLabel.Location = new Point(20, 145);
            phoneLabel.Text = "Telefon:";
            phoneTextBox.Location = new Point(145, 141);
            phoneTextBox.Mask = "(00) 000-00-00";
            phoneTextBox.Size = new Size(155, 23);
            emailLabel.AutoSize = true;
            emailLabel.Location = new Point(20, 197);
            emailLabel.Text = "Email:";
            emailTextBox.Location = new Point(145, 193);
            emailTextBox.Size = new Size(155, 23);
            ticketButton.BackColor = Color.FromArgb(0, 190, 195);
            ticketButton.FlatStyle = FlatStyle.Flat;
            ticketButton.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            ticketButton.ForeColor = Color.White;
            ticketButton.Location = new Point(145, 250);
            ticketButton.Size = new Size(155, 35);
            ticketButton.Text = "Bilet al";
            ticketButton.Click += ticketButton_Click;
            ticketsListBox.FormattingEnabled = true;
            ticketsListBox.ItemHeight = 16;
            ticketsListBox.Location = new Point(40, 485);
            ticketsListBox.Size = new Size(860, 100);
            deleteButton.BackColor = Color.Firebrick;
            deleteButton.ForeColor = Color.White;
            deleteButton.Location = new Point(40, 615);
            deleteButton.Size = new Size(155, 35);
            deleteButton.Text = "Delete ticket";
            deleteButton.Click += deleteButton_Click;
            exitButton.BackColor = Color.Maroon;
            exitButton.ForeColor = Color.White;
            exitButton.Location = new Point(745, 615);
            exitButton.Size = new Size(155, 35);
            exitButton.Text = "Exit";
            exitButton.Click += exitButton_Click;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.Gray;
            ClientSize = new Size(940, 680);
            Controls.Add(deleteButton);
            Controls.Add(exitButton);
            Controls.Add(ticketsListBox);
            Controls.Add(personBox);
            Controls.Add(travelBox);
            Controls.Add(header);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            StartPosition = FormStartPosition.CenterScreen;
            Text = "BMU Travel";
            header.ResumeLayout(false);
            header.PerformLayout();
            travelBox.ResumeLayout(false);
            travelBox.PerformLayout();
            personBox.ResumeLayout(false);
            personBox.PerformLayout();
            ResumeLayout(false);
        }

        private Panel header; private Label universityLabel; private Label titleLabel;
        private GroupBox travelBox; private Button swapButton; private TextBox placeTextBox; private Label placeLabel; private MaskedTextBox timeTextBox; private Label timeLabel; private MaskedTextBox dateTextBox; private Label dateLabel; private ComboBox toComboBox; private Label toLabel; private ComboBox fromComboBox; private Label fromLabel;
        private GroupBox personBox; private Button ticketButton; private TextBox emailTextBox; private Label emailLabel; private MaskedTextBox phoneTextBox; private Label phoneLabel; private TextBox finTextBox; private Label finLabel; private TextBox nameTextBox; private Label nameLabel;
        private ListBox ticketsListBox; private Button deleteButton; private Button exitButton;
    }
}